<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="apd_mm" nsURI="http://www.example.org/apd_mm" nsPrefix="apd_mm">
  <eAnnotations source="http://www.eclipse.org/OCL/Import">
    <details key="ecore" value="http://www.eclipse.org/emf/2002/Ecore"/>
    <details key="ecore.xml.type" value="http://www.eclipse.org/emf/2003/XMLType"/>
  </eAnnotations>
  <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
    <details key="invocationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    <details key="settingDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    <details key="validationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="Alarm">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="volumerange durationsrange intervalsrange repetitionsrange"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="volumerange" value="volume >= 0 and volume &lt;= 5"/>
      <details key="durationsrange" value="duration >= 3 and duration &lt;= 600"/>
      <details key="intervalsrange" value="interval >= 0 and interval &lt;= 60"/>
      <details key="repetitionsrange" value="repetitions >= 0 and repetitions &lt;= 10"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="silent_mode" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="melody" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="volume" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="volume_boost" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="duration" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="interval" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="repetitions" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MedicationPlan">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="pdrange"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="pdrange" value="period_days >= 1 and period_days &lt;= 28"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="first_dose_date" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Date"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="period_days" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="timings" lowerBound="1"
        upperBound="-1" eType="#//IntakeTime" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Connectivity">
    <eLiterals name="Cellular"/>
    <eLiterals name="Wifi" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DateAndTime">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="auto" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="date" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Date"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="time" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Time"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="time_zone" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="use_24h_format" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Setting">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="medrange"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="medrange" value="early_access_to_medication >= 1 and early_access_to_medication &lt;= 300"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="early_access_to_medication"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="alarm" lowerBound="1" eType="#//Alarm"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="language" eType="#//Language"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="connection" eType="#//Connectivity"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="display" lowerBound="1"
        eType="#//Display"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="datetime" lowerBound="1"
        eType="#//DateAndTime"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DeviceStatus">
    <eLiterals name="Good"/>
    <eLiterals name="Test" value="1"/>
    <eLiterals name="Defect" value="2"/>
    <eLiterals name="Scrapped" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Language">
    <eLiterals name="English"/>
    <eLiterals name="Norwegian" value="1"/>
    <eLiterals name="Dutch" value="2"/>
    <eLiterals name="Swedish" value="3"/>
    <eLiterals name="Icelandic" value="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Device">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="typenotnull locationnotnull numberrange"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="typenotnull" value="type &lt;> null"/>
      <details key="locationnotnull" value="location &lt;> null"/>
      <details key="numberrange" value="number > 0"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="status" eType="#//DeviceStatus"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="number" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="location" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="note" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="medicationplan" upperBound="-1"
        eType="#//MedicationPlan" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="settings" lowerBound="1"
        upperBound="-1" eType="#//Setting" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="cartridge" lowerBound="1"
        eType="#//Cartridge" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Display">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="brightnessrange"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="brightnessrange" value="brightness >= 1 and brightness &lt;= 5"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sleep_mode" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="auto_brightness" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="brightness" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Cartridge">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="is_empty" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MedicationLine">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="dosesrange rolls"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="dosesrange" value="doses >= 0 and doses &lt;= 9"/>
      <details key="rolls" value="current_roll = true or next_roll = true"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="doses" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="current_roll" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="next_roll" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IntakeTime">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="time" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Time"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="medications" lowerBound="1"
        upperBound="-1" eType="#//MedicationLine"/>
  </eClassifiers>
</ecore:EPackage>
